import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database} from '@/db/raw';
import {z} from 'zod';
import {communes,examples,demoMakers} from '@/lib/data';
export const dynamic='force-dynamic';
const text=(n:number)=>z.string().trim().min(1).max(n);
const id=text(150);
async function identity(){const u=await getChatGPTUser();if(!u)return null;const db=database();await db.prepare('INSERT INTO users (id,email,name) VALUES (?,?,?) ON CONFLICT(id) DO NOTHING').bind(u.userId,u.email,(u.fullName||u.email.split('@')[0]).slice(0,80)).run();return u.userId;}
export async function GET(){try{const uid=await identity();if(!uid)return Response.json({user:null,requests:[],offers:[],makers:[]});const db=database();const u=await db.prepare('SELECT id,name,role,commune,lat,lng,bio,specialties,base_price FROM users WHERE id=?').bind(uid).first<any>();const r=await db.prepare(`SELECT r.*, (SELECT count(*) FROM offers o WHERE o.request_id=r.id AND o.status='pending') offer_count FROM repair_requests r WHERE r.user_id=? OR (r.is_demo=0 AND ((r.status='open' AND EXISTS (SELECT 1 FROM users u WHERE u.id=? AND u.role='maker')) OR EXISTS(SELECT 1 FROM offers o WHERE o.request_id=r.id AND o.maker_id=?))) ORDER BY r.created_at DESC LIMIT 200`).bind(uid,uid,uid).all();const o=await db.prepare(`SELECT o.*,u.name,v.rating review_rating FROM offers o JOIN users u ON u.id=o.maker_id JOIN repair_requests r ON r.id=o.request_id LEFT JOIN reviews v ON v.offer_id=o.id WHERE r.user_id=? OR o.maker_id=? ORDER BY o.price`).bind(uid,uid).all();const m=await db.prepare(`SELECT u.id,u.name,u.role,u.commune,u.lat,u.lng,u.bio,u.specialties,u.base_price,COALESCE((SELECT avg(r.rating) FROM reviews r JOIN repair_requests q ON q.accepted_offer_id=r.offer_id WHERE r.maker_id=u.id AND q.is_demo=0),0) rating,(SELECT count(*) FROM reviews r JOIN repair_requests q ON q.accepted_offer_id=r.offer_id WHERE r.maker_id=u.id AND q.is_demo=0) rating_count FROM users u WHERE u.role='maker' AND u.id NOT LIKE 'demo-%' LIMIT 200`).all<any>();return Response.json({user:{...u,specialties:JSON.parse(u.specialties)},requests:r.results,offers:o.results,makers:m.results.map(x=>({...x,specialties:JSON.parse(x.specialties)}))},{headers:{'Cache-Control':'no-store'}});}catch(e){console.error('kintsugi GET',e);return Response.json({error:'No pudimos cargar las reparaciones. Reintenta en unos segundos.'},{status:503});}}
export async function POST(req:Request){try{if(req.headers.get('origin')&&new URL(req.headers.get('origin')!).origin!==new URL(req.url).origin)return Response.json({error:'Solicitud de otro origen.'},{status:403});const uid=await identity();if(!uid)return Response.json({error:'Inicia sesión para guardar los cambios.'},{status:401});const db=database();const body=z.record(z.unknown()).parse(await req.json());const action=z.enum(['create','demo','offer','accept','withdraw','complete','cancel','review','profile','joinMaker']).parse(body.action);let result:any;
if(action==='create'){const v=z.object({name:text(120),category:z.enum(['Cerámica','Muebles','Iluminación','Electrónica','Textiles','Otros']),description:text(1000),commune:z.enum(Object.keys(communes) as [string,...string[]]),imageId:id}).parse(body);const owned=await db.prepare('SELECT id FROM images WHERE id=? AND owner_id=?').bind(v.imageId,uid).first();if(!owned)return Response.json({error:'Sube una foto antes de publicar.'},{status:400});const rid=crypto.randomUUID();await db.prepare('INSERT INTO repair_requests (id,user_id,item_name,category,description,image_id,commune) VALUES (?,?,?,?,?,?,?)').bind(rid,uid,v.name,v.category,v.description,v.imageId,v.commune).run();result={id:rid};}
if(action==='demo'){const ex=examples.find(x=>x.id===body.exampleId);if(!ex)return Response.json({error:'Ejemplo no encontrado.'},{status:400});const rid=crypto.randomUUID();const mk=demoMakers[examples.indexOf(ex)];const mk2=mk.id+'-alt';const stmts=[db.prepare('INSERT OR IGNORE INTO users (id,email,name,role,commune,bio,specialties,base_price) VALUES (?,?,?,\'maker\',?,?,?,?)').bind(mk.id,mk.id+'@example.invalid',mk.name,mk.commune,mk.bio,JSON.stringify(mk.specialties),mk.base_price),db.prepare('INSERT OR IGNORE INTO users (id,email,name,role,commune) VALUES (?,?,?,\'maker\',?)').bind(mk2,mk2+'@example.invalid','Taller del Barrio',ex.commune),db.prepare('INSERT INTO repair_requests (id,user_id,item_name,category,description,image_id,commune,is_demo) VALUES (?,?,?,?,?,?,?,1)').bind(rid,uid,ex.item_name,ex.category,ex.description,'sample:'+ex.id,ex.commune),db.prepare('INSERT INTO offers (id,request_id,maker_id,price,message,days) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),rid,mk.id,ex.price,'Revisamos la pieza y recuperamos las partes originales. Incluye materiales y terminación.',4),db.prepare('INSERT INTO offers (id,request_id,maker_id,price,message,days) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),rid,mk2,ex.price+8000,'Podemos reparar tu objeto. El valor incluye revisión y materiales; coordinamos la entrega al aceptar.',7)];await db.batch(stmts);result={id:rid};}
if(action==='offer'){const v=z.object({requestId:id,price:z.number().int().min(1).max(10000000),days:z.number().int().min(1).max(180),message:text(1000)}).parse(body);const oid=crypto.randomUUID();const r=await db.prepare(`INSERT INTO offers (id,request_id,maker_id,price,message,days) SELECT ?,r.id,?,?,?,? FROM repair_requests r JOIN users u ON u.id=? AND u.role='maker' WHERE r.id=? AND r.user_id<>? AND r.status='open' AND r.is_demo=0`).bind(oid,uid,v.price,v.message,v.days,uid,v.requestId,uid).run();if(!r.meta.changes)return Response.json({error:'Esta solicitud no está disponible para recibir tu oferta.'},{status:409});result={id:oid};}
if(action==='accept'){const v=z.object({offerId:id}).parse(body);const resultRows=await db.batch([db.prepare(`UPDATE repair_requests SET status='in_progress',accepted_offer_id=? WHERE user_id=? AND status='open' AND id=(SELECT request_id FROM offers WHERE id=? AND status='pending')`).bind(v.offerId,uid,v.offerId),db.prepare(`UPDATE offers SET status='accepted' WHERE id=? AND EXISTS(SELECT 1 FROM repair_requests r WHERE r.id=offers.request_id AND r.user_id=? AND r.accepted_offer_id=offers.id AND r.status='in_progress')`).bind(v.offerId,uid),db.prepare(`UPDATE offers SET status='rejected' WHERE status='pending' AND id<>? AND request_id=(SELECT id FROM repair_requests WHERE user_id=? AND accepted_offer_id=? AND status='in_progress')`).bind(v.offerId,uid,v.offerId)]);if(!resultRows[0].meta.changes)return Response.json({error:'La oferta ya cambió. Actualiza la solicitud.'},{status:409});}
if(action==='withdraw'){const v=z.object({offerId:id}).parse(body);const r=await db.prepare("UPDATE offers SET status='withdrawn' WHERE id=? AND maker_id=? AND status='pending'").bind(v.offerId,uid).run();if(!r.meta.changes)return Response.json({error:'No puedes retirar esta oferta.'},{status:409});}
if(action==='complete'||action==='cancel'){const v=z.object({requestId:id}).parse(body);if(action==='complete'){const r=await db.prepare("UPDATE repair_requests SET status='completed' WHERE id=? AND user_id=? AND status='in_progress'").bind(v.requestId,uid).run();if(!r.meta.changes)return Response.json({error:'La reparación no está en curso.'},{status:409});}else{const r=await db.batch([db.prepare("UPDATE repair_requests SET status='cancelled' WHERE id=? AND user_id=? AND status IN ('open','in_progress')").bind(v.requestId,uid),db.prepare("UPDATE offers SET status=CASE WHEN status='accepted' THEN 'withdrawn' ELSE 'rejected' END WHERE request_id=? AND status IN ('pending','accepted') AND EXISTS(SELECT 1 FROM repair_requests r WHERE r.id=? AND r.user_id=? AND r.status='cancelled')").bind(v.requestId,v.requestId,uid)]);if(!r[0].meta.changes)return Response.json({error:'Esta solicitud no se puede cancelar.'},{status:409});}}
if(action==='review'){const v=z.object({offerId:id,rating:z.number().int().min(1).max(5),comment:text(1000)}).parse(body);const r=await db.prepare(`INSERT INTO reviews (id,offer_id,reviewer_id,maker_id,rating,comment) SELECT ?,o.id,?,o.maker_id,?,? FROM offers o JOIN repair_requests r ON r.id=o.request_id WHERE o.id=? AND o.status='accepted' AND r.status='completed' AND r.user_id=?`).bind(crypto.randomUUID(),uid,v.rating,v.comment,v.offerId,uid).run();if(!r.meta.changes)return Response.json({error:'Completa la reparación antes de dejar una reseña.'},{status:409});}
if(action==='profile'||action==='joinMaker'){const v=z.object({name:text(80),commune:z.enum(Object.keys(communes) as [string,...string[]]),bio:z.string().trim().max(500),specialties:z.array(z.enum(['Cerámica','Muebles','Iluminación','Electrónica','Textiles','Otros'])).max(6),basePrice:z.number().int().min(0).max(10000000)}).parse(body);if(action==='joinMaker'&&(v.bio.length<10||v.specialties.length===0))return Response.json({error:'Describe tu taller y elige al menos una especialidad.'},{status:400});const [lat,lng]=communes[v.commune];await db.prepare('UPDATE users SET name=?,commune=?,lat=?,lng=?,bio=?,specialties=?,base_price=? WHERE id=?').bind(v.name,v.commune,lat,lng,v.bio,JSON.stringify(v.specialties),v.basePrice,uid).run();if(action==='joinMaker')await db.prepare("UPDATE users SET role='maker' WHERE id=?").bind(uid).run();}
return Response.json({ok:true,...result});}catch(e){if(e instanceof z.ZodError)return Response.json({error:'Revisa los campos: faltan datos o alguno no es válido.'},{status:400});console.error('kintsugi POST',e);if(String(e).includes('UNIQUE'))return Response.json({error:'Ya existe una oferta o reseña para esta reparación.'},{status:409});return Response.json({error:'No pudimos guardar los cambios. Tus datos siguen en el formulario; reintenta.'},{status:503});}}
