const cats=document.getElementById("cats"),title=document.getElementById("title"),products=document.getElementById("products"),order=document.getElementById("order"),total=document.getElementById("total"),mobileTotal=document.getElementById("mobileTotal"),ticket=document.getElementById("ticket"),serviceLabel=document.getElementById("serviceLabel");
const items=[["Bar","Negroni Boldo","Gin / rosso / bitter / boldo",7200],["Bar","Spritz Costa","Pomelo / espumante / soda",6900],["Bar","Sour Ahumado","Pisco / limón / humo / bitter",6800],["Bar","Highball Salino","Whisky / soda / sal marina",7400],["Cocina","Burger Fuego","Vacuno / cheddar / encurtido / brioche",11900],["Cocina","Pollo Crispy","Pollo / ají / miel / pickles",9900],["Cocina","Papas Bravas","Papa / salsa fuego / ajo",6200],["Sin alcohol","Pomelo Tonic","Pomelo / tónica / romero",4200],["Sin alcohol","Jengibre Soda","Jengibre / limón / soda",3900]].map((x,i)=>({id:i+1,cat:x[0],name:x[1],desc:x[2],price:x[3]}));
let cat="Todo",basket=[],svc="MESA";const money=n=>"$"+n.toLocaleString("es-CL");const cs=["Todo","Bar","Cocina","Sin alcohol"];try{const old=JSON.parse(localStorage.getItem('fuego-cart-v1'));if(Array.isArray(old))basket=old.filter(x=>x&&items.some(p=>p.id===x.id)&&Number.isInteger(x.qty)&&x.qty>0&&x.qty<=20)}catch{}function save(){try{localStorage.setItem('fuego-cart-v1',JSON.stringify(basket))}catch{}}
function renderCats(){cats.innerHTML=cs.map(x=>'<button class="'+(x===cat?'on':'')+'" data-click="pick(\''+x+'\')">'+x+'</button>').join("")}
function pick(x){cat=x;title.innerHTML=x==="Todo"?"Toda<br>la barra.":x+".";renderCats();render()}
function render(){const list=items.filter(x=>cat==="Todo"||x.cat===cat);products.innerHTML=list.map((x,i)=>'<div class="product" style="--row:'+i+'"><span class="num">'+String(i+1).padStart(2,"0")+'</span><div><h2>'+x.name+'</h2><p>'+x.desc+'</p></div><span class="price">'+money(x.price)+'</span><button class="plus" data-click="add('+x.id+')">+</button></div>').join("")}
function add(id){const x=basket.find(y=>y.id===id);if(x)x.qty=Math.min(20,x.qty+1);else basket.push({id,qty:1});save();renderOrder();document.querySelectorAll(".total,.mobile-ticket").forEach(el=>{el.classList.remove("updated");void el.offsetWidth;el.classList.add("updated")});toast("SUMADO A COMANDA")}
function remove(id){const x=basket.find(y=>y.id===id);if(!x)return;x.qty--;if(x.qty<1)basket=basket.filter(y=>y.id!==id);save();renderOrder()}
function renderOrder(){let sum=0;order.innerHTML=basket.length?basket.map(x=>{const p=items.find(y=>y.id===x.id);sum+=p.price*x.qty;return '<div class="order-row"><span>'+String(x.qty).padStart(2,"0")+' × '+p.name+'<br><button data-click="remove('+x.id+')">− QUITAR UNO</button></span><b>'+money(p.price*x.qty)+'</b></div>'}).join(""):'<div class="empty">COMANDA VACÍA.<br>SELECCIONA PRODUCTOS DESDE LA CARTA.</div>';total.textContent=mobileTotal.textContent=money(sum);const send=document.querySelector('.send');if(send)send.disabled=!basket.length}
function service(btn,s){svc=s;document.querySelectorAll(".service button").forEach(x=>x.classList.remove("on"));btn.classList.add("on");serviceLabel.textContent="SERVICIO · "+s}
function toast(s){const t=document.getElementById("toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1100)}
renderCats();render();renderOrder();const send=document.querySelector('.send');send.removeAttribute('data-click');send.textContent='Preparar comanda';send.disabled=!basket.length;let receiptText='';send.addEventListener('click',()=>{if(!basket.length)return;receiptText='FUEGO / COMANDA DEMOSTRATIVA\n'+new Date().toLocaleString('es-CL')+' · '+svc+'\n\n'+basket.map(x=>{const p=items.find(y=>y.id===x.id);return x.qty+' × '+p.name+' — '+money(p.price*x.qty)}).join('\n')+'\n\nTOTAL: '+money(basket.reduce((n,x)=>n+items.find(y=>y.id===x.id).price*x.qty,0))+'\n\nSin envío ni cobro real.';document.getElementById('receipt-content').textContent=receiptText;ticket.classList.remove('open');document.getElementById('receipt').showModal()});document.getElementById('close-receipt').onclick=()=>document.getElementById('receipt').close();document.getElementById('save-receipt').onclick=()=>{const url=URL.createObjectURL(new Blob([receiptText],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='fuego-comanda.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};document.getElementById('new-receipt').onclick=()=>{basket=[];save();renderOrder();document.getElementById('receipt').close()};

function closeTicket(){ticket.classList.remove("open")}function openTicket(){ticket.classList.add("open")}

const cardActions={pick,add,remove,service,toast,openTicket,closeTicket};
function dispatchCard(event,attribute){const el=event.target.closest('['+attribute+']');if(!el)return;const expression=el.getAttribute(attribute),match=expression.match(/^(\w+)\((.*)\)$/);if(!match||!cardActions[match[1]])return;const args=(match[2].match(/'[^']*'|"[^"]*"|[^,]+/g)||[]).map(x=>{x=x.trim();if(x==='this')return el;if(x==='event')return event;if(x==='this.value')return el.value;if(/^['"]/.test(x))return x.slice(1,-1);return Number(x)});cardActions[match[1]](...args)}
document.addEventListener('click',e=>dispatchCard(e,'data-click'));document.addEventListener('change',e=>dispatchCard(e,'data-change'));
/*document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelectorAll('.overlay.open').forEach(el=>closeOverlay(el.id));}});*/
