(()=>{'use strict';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(n),norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const dishes=[
{id:'ceviche',name:'Ceviche de reineta',cat:'Del mar',price:11800,desc:'Reineta, leche de tigre, cebolla morada y cilantro. Fresco y cítrico.',all:'Pescado',art:'fish'},
{id:'pesca',name:'Pesca a la mantequilla',cat:'Del mar',price:15900,desc:'Pesca blanca, papas nuevas, mantequilla de hierbas y limón.',all:'Pescado · leche',art:'fish'},
{id:'ostiones',name:'Ostiones gratinados',cat:'Para compartir',price:13900,desc:'Seis ostiones al horno, parmesano y mantequilla de la casa.',all:'Moluscos · leche',art:'shell'},
{id:'empanadas',name:'Empanadas de jaiba',cat:'Para compartir',price:9900,desc:'Cuatro empanadas crujientes con jaiba, cebolla y merkén.',all:'Crustáceos · trigo · leche',art:'shell'},
{id:'coliflor',name:'Coliflor al rescoldo',cat:'De la huerta',price:10900,desc:'Coliflor asada, crema de semillas y chimichurri.',all:'Sésamo',art:'leaf',veg:true},
{id:'tomates',name:'Tomates de estación',cat:'De la huerta',price:7900,desc:'Tomates, albahaca, aceite de oliva y tostadas de masa madre.',all:'Trigo',art:'leaf',veg:true},
{id:'limonada',name:'Limonada de huerto',cat:'Para beber',price:3900,desc:'Limón, pepino y albahaca. Sin alcohol.',all:'Revisar preparación en local',art:'glass',veg:true},
{id:'pomelo',name:'Pomelo & romero',cat:'Para beber',price:4500,desc:'Pomelo rosado, soda y romero fresco. Sin alcohol.',all:'Revisar preparación en local',art:'glass',veg:true}];
let raw;try{raw=JSON.parse(localStorage.getItem('marea-cart-v2'))}catch{}let cart=Array.isArray(raw)?raw.filter(x=>x&&dishes.some(d=>d.id===x.id)&&Number.isInteger(x.qty)&&x.qty>0&&x.qty<=20):[];cart=cart.filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i);let cat='Toda la carta',receipt='';
const save=()=>{try{localStorage.setItem('marea-cart-v2',JSON.stringify(cart));return true}catch{return false}};
const toast=s=>{$('#toast').textContent=s;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').textContent='',2200)};
function render(){const q=norm($('#search').value.trim()),list=dishes.filter(d=>(cat==='Toda la carta'||d.cat===cat)&&($('#diet').value!=='vegetarian'||d.veg)&&norm(d.name+' '+d.desc).includes(q));$('#results').textContent=list.length+' opciones / precios en CLP';$('#dishes').innerHTML=list.length?list.map(d=>'<article class="dish"><div class="dish-art"><img src="assets/marea/'+d.id+'.webp" alt="'+d.name+'" width="960" height="640" loading="lazy" decoding="async"></div><div class="dish-body"><span class="eyebrow">'+d.cat+'</span><h3>'+d.name+'</h3><p>'+d.desc+'</p><small>'+(d.veg?'Vegetariano · ':'')+'Alérgenos: '+d.all+'</small><div class="dish-foot"><strong>'+money(d.price)+'</strong><button data-add="'+d.id+'" aria-label="Agregar '+d.name+'">Agregar +</button></div></div></article>').join(''):'<p class="empty">No encontramos platos con esos filtros. Prueba otra búsqueda.</p>';$$('[data-cat]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.cat===cat)))}
function totals(){const subtotal=cart.reduce((n,x)=>n+dishes.find(d=>d.id===x.id).price*x.qty,0),tip=$('#tip').checked?Math.round(subtotal*.1):0,people=Number($('#people').value)||1;$('#subtotal').textContent=money(subtotal);$('#tip-value').textContent=money(tip);$('#total').textContent=money(subtotal+tip);$('#per-person').textContent=money(Math.ceil((subtotal+tip)/people));$('#make-order').disabled=!cart.length;$('#bar-total').textContent=money(subtotal);$('#cart-count').textContent=cart.reduce((n,x)=>n+x.qty,0)+' productos';return{subtotal,tip}}
function renderCart(){const box=$('#cart-items');box.replaceChildren();if(!cart.length){const p=document.createElement('p');p.textContent='Tu mesa todavía está por armar. Elige algo de la carta.';box.append(p)}cart.forEach(x=>{const d=dishes.find(d=>d.id===x.id),row=document.createElement('div');row.className='cart-row';row.innerHTML='<div><h3>'+d.name+'</h3><small>'+money(d.price)+' por unidad</small><div class="quantity"><button data-minus="'+d.id+'" aria-label="Quitar '+d.name+'">−</button><span>'+x.qty+'</span><button data-plus="'+d.id+'" aria-label="Sumar '+d.name+'" '+(x.qty>=20?'disabled':'')+'>+</button></div></div><span>'+money(d.price*x.qty)+'</span>';box.append(row)});totals()}
function change(id,delta){if(!dishes.some(d=>d.id===id))return;const x=cart.find(x=>x.id===id);if(x){x.qty=Math.min(20,x.qty+delta);if(x.qty<1)cart=cart.filter(y=>y!==x)}else if(delta>0)cart.push({id,qty:1});if(!save())toast('Selección conservada sólo durante esta sesión.');renderCart()}
$('#filters').innerHTML=['Toda la carta','Para compartir','Del mar','De la huerta','Para beber'].map(x=>'<button data-cat="'+x+'" aria-pressed="'+(x===cat)+'">'+x+'</button>').join('');
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.add){change(b.dataset.add,1);toast('Agregado a tu mesa.')}if(b.dataset.plus)change(b.dataset.plus,1);if(b.dataset.minus)change(b.dataset.minus,-1);if(b.dataset.cat){cat=b.dataset.cat;render()}if(b.hasAttribute('data-close'))b.closest('dialog').close()});$('#search').addEventListener('input',render);$('#diet').addEventListener('change',render);$('#tip').addEventListener('change',totals);$('#people').addEventListener('change',totals);$('#open-cart').addEventListener('click',()=>{renderCart();$('#order').showModal()});
$('#order-form').addEventListener('submit',e=>{e.preventDefault();if(!cart.length)return;const {subtotal,tip}=totals();receipt='MAREA / COMANDA DE DEMOSTRACIÓN\n'+new Date().toLocaleString('es-CL')+' · '+$('#table').value+'\n\n'+cart.map(x=>{const d=dishes.find(d=>d.id===x.id);return x.qty+' × '+d.name+' — '+money(d.price*x.qty)}).join('\n')+'\n\nSubtotal: '+money(subtotal)+'\nPropina voluntaria: '+money(tip)+'\nTotal: '+money(subtotal+tip)+'\nPor persona (redondeado): '+$('#per-person').textContent+'\nObservaciones: '+($('#notes').value.trim()||'Sin observaciones')+'\n\nSin envío a cocina ni cobro. Precios demostrativos.';$('#receipt-text').textContent=receipt;$('#order').close();$('#receipt').showModal()});
$('#download').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([receipt],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='marea-comanda.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});$('#edit-order').addEventListener('click',()=>{$('#receipt').close();$('#order').showModal()});$('#new-order').addEventListener('click',()=>{cart=[];save();$('#order-form').reset();renderCart();$('#receipt').close();toast('Mesa lista para una nueva selección.')});render();renderCart()})();
