/* DOM behavior checks (jsdom). Not a browser/rendering/accessibility audit.
   npm install --prefix tools/qa jsdom@26
   NODE_PATH=tools/qa/node_modules node tools/functional-tests.cjs */
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
let JSDOM;try{({JSDOM}=require('jsdom'))}catch{({JSDOM}=require('./qa/node_modules/jsdom'))}
const root=path.resolve(__dirname,'..');let assertions=0;const results=[];
function ok(condition,label){assert.ok(condition,label);assertions++;results.push(label)}
function eq(a,b,label){assert.deepEqual(a,b,label);assertions++;results.push(label)}
function app(page,script,storage={}){const dom=new JSDOM(fs.readFileSync(path.join(root,page),'utf8'),{url:'https://portfolio.test/'+page,runScripts:'outside-only'});const w=dom.window;w.structuredClone=structuredClone;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.print=()=>{w.printed=true};for(const [k,v]of Object.entries(storage))w.localStorage.setItem(k,v);const files=['common'];if(script==='commerce')files.push('catalog');files.push(script);let code=files.map(n=>fs.readFileSync(path.join(root,'js',n+'.js'),'utf8').replace(/^import[\s\S]*?;\s*$/gm,'').replace(/^export /gm,'')).join('\n');w.eval(code);return {w,d:w.document,$:s=>w.document.querySelector(s),click:s=>{const el=w.document.querySelector(s);assert.ok(el,'Missing '+s);el.click()},set:(s,v)=>{const el=w.document.querySelector(s);el.value=v;el.dispatchEvent(new w.Event('input',{bubbles:true}));el.dispatchEvent(new w.Event('change',{bubbles:true}))},storage:()=>Object.fromEntries(Array.from({length:w.localStorage.length},(_,i)=>{const k=w.localStorage.key(i);return [k,w.localStorage.getItem(k)]}))}}
for(const [page,key]of [['demo-tienda.html','nc-shop-v2'],['demo-artista.html','nc-artist-v2']]){
 let a=app(page,'commerce');eq(a.d.querySelectorAll('.product').length,3,page+' renders three products');a.click('[data-add]');eq(a.$('#cart-count').textContent,'1',page+' adds product');ok(a.$('#cart').open,'cart opens');a.click('[data-plus]');eq(a.$('#cart-count').textContent,'2','quantity increments');ok(a.$('.total-row strong').textContent.includes(page.includes('tienda')?'91.980':'49.980'),'quantity changes total');a=app(page,'commerce',a.storage());eq(a.$('#cart-count').textContent,'2','cart survives reinitialization');a.click('#cart-open');a.click('#checkout');ok(a.$('#finish-demo').disabled,'checkout requires demo acknowledgement');a.click('#demo-ack');a.click('#finish-demo');ok(a.$('#cart').textContent.includes('No se creó un pedido'),'checkout honest completion');a.click('#continue');a.click('#cart-open');a.click('[data-minus]');eq(a.$('#cart-count').textContent,'1','quantity decrements');a.click('[data-remove]');eq(a.$('#cart-count').textContent,'0','remove empties cart');ok(a.$('#checkout').disabled,'empty checkout disabled');a.click('#cart [data-close]');a.click('[data-detail]');ok(a.$('#product-detail').open,'product detail opens');
 if(page.includes('tienda')){a.click('#product-detail [data-close]');a.click('[data-filter="Audio"]');eq(a.d.querySelectorAll('.product').length,1,'category filter');}
 const broken=app(page,'commerce',{[key]:'{bad-json'});eq(broken.$('#cart-count').textContent,'0','corrupt cart recovered');ok(broken.$('#global-status').textContent.includes('No se pudieron'),'corruption communicated');
 const invalid=app(page,'commerce',{[key]:JSON.stringify([{id:'unknown',qty:-1}])});eq(invalid.$('#cart-count').textContent,'0','invalid product rejected');
}
let a=app('demo-dental.html','dental');eq(a.d.querySelectorAll('.day').length,7,'agenda renders seven dates');eq(a.d.querySelectorAll('.appointment').length,2,'seed appointments');a.click('#next');eq(a.d.querySelectorAll('.appointment').length,0,'appointments do not repeat next week');a.click('#previous');a.click('#new-appointment');a.set('#patient','Paciente ficticio C');a.set('#reason','Prueba');a.set('#appointment-time','09:30');a.$('#appointment-form').requestSubmit();ok(a.$('#appointment-error').textContent.includes('cruza'),'overlap blocked over duration');a.set('#appointment-time','10:00');a.$('#appointment-form').requestSubmit();ok(!a.$('#appointment').open,'adjacent appointment accepted');eq(a.d.querySelectorAll('.appointment').length,3,'appointment created');a=app('demo-dental.html','dental',a.storage());eq(a.d.querySelectorAll('.appointment').length,3,'agenda persists');const created=[...a.d.querySelectorAll('.appointment')].find(e=>e.textContent.includes('ficticio C'));created.click();a.set('#duration','90');a.set('#appointment-time','18:00');a.$('#appointment-form').requestSubmit();ok(a.$('#appointment-error').textContent.includes('19:00'),'closing-hour duration checked');a.set('#appointment-time','12:00');a.$('#appointment-form').requestSubmit();ok(!a.$('#appointment').open,'edit saved');a.set('#professional-filter','Dr. Rojas');eq(a.d.querySelectorAll('.appointment').length,1,'professional filter');a.set('#professional-filter','all');[...a.d.querySelectorAll('.appointment')].find(e=>e.textContent.includes('ficticio C')).click();a.click('#remove-appointment');eq(a.d.querySelectorAll('.appointment').length,2,'appointment removed');a.click('#undo-delete');eq(a.d.querySelectorAll('.appointment').length,3,'appointment removal undo');a.click('#new-appointment');a.set('#patient','<img src=x onerror=alert(1)>');a.set('#reason','Safe string');a.set('#appointment-time','16:00');a.$('#appointment-form').requestSubmit();eq(a.d.querySelectorAll('.appointment img').length,0,'patient text escaped');const badAgenda=app('demo-dental.html','dental',{'nc-agenda-v2':'[{"day":0}]'});eq(badAgenda.d.querySelectorAll('.appointment').length,2,'legacy agenda invalid shape recovered');
a=app('demo-cotizador.html','quote');ok(a.$('#quote-totals').textContent.includes('90.000'),'initial quote total');a.set('.tax','19');a.set('#discount','10000');a.set('#charge','5000');ok(a.$('#quote-totals').lastElementChild.textContent.includes('100.200'),'discount before 19 percent tax and charge');a.$('#quote-form').requestSubmit();ok(a.$('#quote-status').textContent.includes('guardada'),'quote saved');let storage=a.storage();a=app('demo-cotizador.html','quote',storage);a.set('#saved-quotes',a.$('#saved-quotes').options[1].value);a.click('#load-quote');eq(a.$('#discount').value,'10000','saved discount restored');eq(a.$('#charge').value,'5000','saved charge restored');eq(a.$('.tax').value,'19','tax restored');a.click('#print-quote');ok(a.w.printed,'print invoked on valid quote');ok(a.$('#print-sheet').textContent.includes('100.200'),'print contains computed total');a.set('#discount','90001');ok(!a.$('#discount').checkValidity(),'excess discount rejected');a.w.printed=false;a.click('#print-quote');ok(!a.w.printed,'invalid print blocked');a.set('#discount','0');a.set('.qty','-1');ok(!a.$('.qty').checkValidity(),'negative quantity rejected');a.set('.qty','1.5');ok(!a.$('.qty').checkValidity(),'fractional quantity rejected');a.set('.qty','1');a.set('.price','-2');ok(!a.$('.price').checkValidity(),'negative price rejected');a.set('.price','90000');a.set('.description','<script>alert(1)</script>');eq(a.d.querySelectorAll('#print-sheet script').length,0,'quote text escaped in print');
// Round exactly across lines; tax is calculated after the allocated discount.
a.set('.description','A');a.set('.price','1');a.set('.tax','19');a.set('#charge','0');a.click('#add-item');a.set('.quote-item:last-child .price','1');a.set('.quote-item:last-child .tax','19');a.set('#discount','1');ok(a.$('#quote-totals').lastElementChild.textContent.includes('$1'),'rounding distributes full discount');a.$('#quote-form').requestSubmit();a.click('#delete-quote');eq(a.$('#saved-quotes').options.length,1,'quote deleted');a.click('#quote-status button');eq(a.$('#saved-quotes').options.length,2,'quote restored');const badQuote=app('demo-cotizador.html','quote',{'nc-quotes-v2':'[null]'});eq(badQuote.$('#saved-quotes').options.length,1,'corrupt quotes recover');
a=app('demo-institucional.html','portal');eq(a.d.querySelectorAll('.service-card').length,6,'six services rendered');a.set('#service-search','certificados');eq(a.d.querySelectorAll('.service-card').length,1,'service search');a.click('[data-service]');ok(a.$('#service-detail').textContent.includes('no se emiten certificados'),'service content truthful');a.click('#service-detail [data-close]');a.set('#service-search','zzzz');eq(a.d.querySelectorAll('.service-card').length,0,'empty search state');a.set('#service-search','');a.click('[data-category="Ayuda"]');eq(a.d.querySelectorAll('.service-card').length,3,'service category filter');a.set('#edit-title','Nuevo título de prueba');a.set('#edit-copy','Contenido ficticio editado');a.$('#editor-form').requestSubmit();eq(a.$('#hero-title').textContent,'Nuevo título de prueba','editor updates hero');a=app('demo-institucional.html','portal',a.storage());eq(a.$('#hero-title').textContent,'Nuevo título de prueba','editor survives reload');a.set('#edit-title','<img src=x onerror=alert(1)>');a.$('#editor-form').requestSubmit();eq(a.$('#hero-title').children.length,0,'editor strings safe');a.click('#reset-editor');eq(a.$('#hero-title').textContent,'Lo que necesitas. Más cerca.','editor reset');a=app('demo-institucional.html','portal',{'nc-portal-v2':'null'});ok(a.$('#hero-title').textContent.includes('Más cerca'),'corrupt editor state recovers');
// Storage write denial never announces a successful save.
a=app('demo-institucional.html','portal');a.w.Storage.prototype.setItem=function(){throw Error('blocked')};a.$('#editor-form').requestSubmit();ok(a.$('#editor-status').textContent.includes('solo en esta sesión'),'storage blocked handled');
console.log(JSON.stringify({assertions,passed:results,limits:'jsdom DOM tests only; no browser layout, focus trapping, audio playback, WebGL or responsive verification.'},null,2));
